# language: en
# Maps to:
#   - docs/specs/phases/phase-38-embedding-remote-reranker-live.md
#   - docs/specs/tasks/task-38.1-remote-reranker-provider-and-live-recall.md
#   - docs/specs/tasks/task-38.2-reranker-config-bridge-and-data-plane-wiring.md
#   - docs/specs/tasks/task-38.3-closeout-v0.31.0.md
#
# 轻量 BDD（s2v §9.2）；Phase 38 embedding-remote-reranker-live（兑现 [SPEC-DEFER:phase-future.embedding-remote-reranker-live]——首次构建 RemoteRerankerProvider + select_reranker 工厂、对真实远程 reranker（cross-encoder over HTTP）端点做端到端联调 + 实测 rerank 质量、并首次把 reranker 从 config 在生产数据面路径 opt-in 接线。在此之前仓库有 Reranker trait + IdentityReranker + feature-gated CrossEncoderReranker（ADR-026），但 RemoteRerankerProvider 不存在、select_reranker 工厂不存在、reranker 至今从未由 config 在生产路径接线（server.rs hybrid:334 / semantic:376 + data_plane/search.rs semantic:282 三处只调 with_embedder().with_vector_searcher()、从不调 with_reranker()，reranker 仅 Phase 21 的 opt-in builder seam 仅测试用）。ADR-013 诚实优先：本机真实 run 实测 MRR/recall@1 仅在 task-38.1 §10 与 ADR-043 D2 引用且标注为主 agent 本机真实 run，规划阶段绝不预填）。Scenario ID 在各 task spec §7 追踪表映射到测试 / 真实 run。
# Status: Draft（规划稿，本文件随 phase/task spec 一并 Draft）。
# 默认构建不变：reranker-remote 为 opt-in，默认构建 0-network / 0 NEW dep（ureq 自 task-22.3 已 optional，新增 feature reranker-remote = ["dep:ureq"] 复用既有 ureq）；0 schema migration；0 proto 改动；数据面默认 CONTEXTFORGE_RERANKER_PROVIDER unset → 字节等价无 rerank（向后兼容，当前行为不变，ADR-004/008）。harness 复用既有 factory.rs（embedding/factory.rs:27-96）的 env 读取范式 + CrossEncoderReranker 的 by-index 映射范式，build_rerank_request_body/parse_rerank_response 为纯函数契约层 + ureq POST（Debug 不打印 api_key），CONTEXTFORGE_RERANKER_API_KEY 仅由用户设 env、永不记录 / 永不进 config。
# 受阻 / 据实非问题维度均以 [SPEC-DEFER:phase-future.<name>] 标注（无 API key 时 honest-defer 干净 skip 不 fail；大语料 rerank 质量 NDCG/MRR 大基准需更大语料延后；CI 跑 live remote rerank 因 remote 付费 API 无免费 service container 复用既有 embedding-remote-ci-credential；多 provider rerank live 矩阵续 embedding-multi-provider-live），据真实本机已认证 run 回填，绝不预填 release 数值（ADR-013，placeholder 待回填 / floor-only）。

Feature: phase-38-embedding-remote-reranker-live
  In order to 把 reranker 维度（ADR-026 已确立 Reranker trait + IdentityReranker + feature-gated CrossEncoderReranker，但 RemoteRerankerProvider 不存在、select_reranker 工厂不存在、reranker 从未在生产数据面路径接线）从 [SPEC-DEFER:phase-future.embedding-remote-reranker-live] 的 honest-defer 状态推进为「真实构建 + 真实测得 + env-gated harness 守护 + 生产数据面 opt-in 接通」（leader 已 DE-RISK 证明：SiliconFlow https://api.siliconflow.cn/v1/rerank + Qwen/Qwen3-VL-Reranker-8B 端到端 round-trip 跑通——查询「如何保存配置到文件」对 4 文档 rerank，相关文档 config_save relevance_score=0.7356 排 #1、近义干扰 config_load=0.0158 排 #2、无关项 ~0.0006/0.0003，HTTP 200，约 46x 区分度，证明端点可用 + 排序语义正确）
  As Phase 38 内核（构建 RemoteRerankerProvider + select_reranker 工厂 + 契约测试 + env-gated remote reranker live harness 在同一作者标注 query×candidate 集上度量 real remote cross-encoder vs IdentityReranker no-semantic-signal 基线的 MRR / recall@1 + Go [reranker] 段 config round-trip + setRerankerEnv env-bridge + Rust 数据面 reranker_from_env() opt-in 接线 + v0.31.0 closeout）
  I want 新增 core/src/rerank/remote_provider.rs（RemoteRerankerProvider：build_rerank_request_body/parse_rerank_response 纯函数 + ureq POST，镜像 RemoteEmbeddingProvider 的结构与 CrossEncoderReranker 的 by-index 映射，Debug 不打印 api_key）+ core/src/rerank/factory.rs（select_reranker(name) 工厂，镜像 embedding/factory.rs:27-96 的 "remote" 分支从 env 读 CONTEXTFORGE_RERANKER_ENDPOINT/_MODEL/_PROVIDER/_API_KEY、feature-off 显式 Err 不静默）+ 新 feature reranker-remote = ["dep:ureq"]（复用既有 ureq，0 新 dep）+ 新增 core/tests/remote_rerank_recall.rs（#![cfg(feature = "reranker-remote")]，env-gated on CONTEXTFORGE_RERANKER_API_KEY），用作者手工标注 query×candidate 集（每 query 一个已知相关文档 + 近义干扰，镜像 embedding harness 的 docs()/cases() 风格故意埋近义干扰），把候选喂入时携带统一 / 无相关性先验 score（IdentityReranker 决定性 tie-break ≈ chance 的 no-semantic-signal 基线），对每个标注 query 用 real remote cross-encoder 与 IdentityReranker 各 rerank，MRR = mean(1/rank_of_relevant)、recall@1 = mean(命中 relevant id at #1)，先 eprintln 真实测得数再 assert（floor MRR_remote >= 0.70 且 MRR_remote > MRR_identity，guard）；当 CONTEXTFORGE_RERANKER_API_KEY 未设时 eprintln 一条 skip 提示并 return（honest-defer，CI 无密钥干净 skip 而非 fail，api_key 永不记录）；另有一个非网络契约 + well-formed 守护测试（build_rerank_request_body/parse_rerank_response fixture 契约 + select_reranker 路由 + 标注集 well-formed：doc id 唯一 / 每个 relevant id 存在 / case 数 >= 12）无 key 也总是跑；Go internal/config/config.go 新增 RerankerConfig（Enabled/Provider/Endpoint/Model，toml round-trip 保真，无 api-key 字段）+ 新 setRerankerEnv helper 镜像 setRemoteEnv / setVectorEnv 跨进程 env-bridge（[reranker] 段存在且对应 env 未设时导出 CONTEXTFORGE_RERANKER_ENDPOINT/_MODEL/_PROVIDER 给 spawned core，ENV WINS，无 [reranker] 段 → 不导出 → 默认行为不变，API KEY 永不进 config）接线进 doServe + doMCP；Rust 数据面新增 reranker_from_env()（读 CONTEXTFORGE_RERANKER_PROVIDER → 非空 / 非 none 时 select_reranker → with_reranker）在 server.rs hybrid:334 / semantic:376 + data_plane/search.rs semantic:282 三处生产路径 opt-in 接线，且默认 CONTEXTFORGE_RERANKER_PROVIDER unset → 无 reranker provenance marker、向后兼容字节等价无 rerank，且默认构建仍 0 NEW dep / 0-network / 0 schema migration / 0 proto / 默认行为不变（ADR-004/008——reranker-remote opt-in、ureq 自 task-22.3 已 optional、Rust core 0 toml dep 复用既有 factory env 路径），harness 度量为作者小型手工标注集（大语料 rerank 质量需更大基准，作为更干净主指标外的延后项 [SPEC-DEFER:phase-future.reranker-large-corpus-quality]）

  # ---
  # Maps to: docs/specs/tasks/task-38.1-remote-reranker-provider-and-live-recall.md (TEST-38.1.1)
  Scenario: SCEN-38.1.1 — 对应 AC1（构建 RemoteRerankerProvider + select_reranker 工厂 + remote reranker live harness 在同一标注 query×candidate 集上度量 real cross-encoder vs IdentityReranker MRR / recall@1 >= floor + remote > identity + eprintln 真实数）
    Given core/src/rerank/remote_provider.rs 的 RemoteRerankerProvider（build_rerank_request_body/parse_rerank_response 纯函数 + ureq POST，镜像 RemoteEmbeddingProvider 与 CrossEncoderReranker 的 by-index 映射）与 core/src/rerank/factory.rs 的 select_reranker(name) 工厂均已构建；core/tests/remote_rerank_recall.rs 以 #![cfg(feature = "reranker-remote")] 门控、env-gated on CONTEXTFORGE_RERANKER_API_KEY（factory 另读 CONTEXTFORGE_RERANKER_ENDPOINT/_MODEL/_PROVIDER，api_key 永不记录）；当 CONTEXTFORGE_RERANKER_API_KEY 已设时一个真实远程 reranker 端点可达；leader 的 DE-RISK 已证明 SiliconFlow https://api.siliconflow.cn/v1/rerank + Qwen/Qwen3-VL-Reranker-8B 端到端 round-trip 跑通（请求 {model, query, documents:[字符串], top_n, return_documents:false}、响应 {results:[{index, relevance_score}], meta}、HTTP 200、排序语义正确、约 46x 区分度）；IdentityReranker 为 no-semantic-signal 基线（候选喂入时携带统一 / 无相关性先验 score，决定性 tie-break ≈ chance）
    When  用作者手工标注 query×candidate 集（每 query 一个已知相关文档 + 故意近义干扰，镜像 embedding harness 的 docs()/cases() 风格），real remote cross-encoder 经 select_reranker("remote") 路由 → RemoteRerankerProvider 把 candidates 的 documents 文本 + query POST 到 live 端点、映射回 candidates[index] 并 set score=relevance_score、annotate reason；IdentityReranker 对同一候选集决定性 rerank；对每个标注 query 算 MRR = mean(1/rank_of_relevant) 与 recall@1 = mean(命中 relevant id at #1)
    Then  先 eprintln 真实测得 remote / identity MRR / recall@1 再 assert：floor MRR_remote >= 0.70（guard）且 MRR_remote > MRR_identity（real cross-encoder 用 query×doc 语义把相关文档排到 #1、IdentityReranker no-semantic-signal 基线 ≈ chance）+ 真实测得数在 task-38.1 §10 与 ADR-043 D2 据实记录并标注为主 agent 本机真实 SiliconFlow run（floor-only 不预填，ADR-013 不伪造；de-risk 探针 config_save relevance_score=0.7356 排 #1 可引用为可行性证据）+ 0 NEW dep / 0 schema migration / 0 proto / 0 默认构建变更（TEST-38.1.1，env-gated，对 live remote 端点真实测试通过后回填真实数）

  # ---
  # Maps to: docs/specs/tasks/task-38.1-remote-reranker-provider-and-live-recall.md (TEST-38.1.2)
  Scenario: SCEN-38.1.2 — 对应 AC2（非网络契约 + select_reranker 路由 + well-formed 守护测试无 key 也总是跑，api_key 永不记录）
    Given 本地 / CI 无 CONTEXTFORGE_RERANKER_API_KEY 时 harness 无远程端点可达（CI 无密钥）；build_rerank_request_body/parse_rerank_response 为纯函数契约层（不依赖网络）；select_reranker 工厂路由（identity / cross-encoder / remote 分支，feature-off 显式 Err）；作者标注 query×candidate 集（doc id / relevant id / case 数）不依赖任何网络；api_key 仅由用户设 env、永不记录 / 永不进 config（PRD 安全基线）
    When  harness 在 CONTEXTFORGE_RERANKER_API_KEY 未设时 eprintln 一条 skip 提示并 return（honest-defer，不 fail test）；并在无 key 路径下跑非网络契约 + well-formed 守护测试，校验 build_rerank_request_body 产出 {model, query, documents, top_n, return_documents:false} fixture 一致 + parse_rerank_response 把 {results:[{index, relevance_score}]} fixture 映射回 candidates[index]、set score、annotate reason + select_reranker 路由分支 + 标注集 doc id 唯一 / 每个 relevant id 存在于候选集 / case 数 >= 12
    Then  无 key → live rerank harness 干净 skip（eprintln 提示，return，NOT fail；CI/本地无密钥不红，honest-defer 非伪绿）+ 非网络契约 + well-formed 守护测试无 key 也总是跑且通过（build/parse fixture 契约 + select_reranker 路由 + doc id 唯一 / 每个 relevant id 存在 / case 数 >= 12，behavior-lock guard）+ api_key 永不出现在任何日志 / 输出 / Debug（PRD 安全基线，RemoteRerankerProvider Debug 不打印 api_key）+ 0 NEW dep（TEST-38.1.2，无 key 即可跑，契约 + well-formed 守护为真实 RED→GREEN）

  # ---
  # Maps to: docs/specs/tasks/task-38.2-reranker-config-bridge-and-data-plane-wiring.md (TEST-38.2.1 / TEST-38.2.2)
  Scenario: SCEN-38.2.1 — 对应 AC3（Go [reranker] 段 round-trip + setRerankerEnv env-bridge env-wins，API key 永不进 config，无 [reranker] 段行为不变）
    Given internal/config/config.go 现有 RemoteProviderConfig（Phase 37 add-only Model）与 setRemoteEnv 跨进程 env-bridge 范式（[remote] 段存在且 env 未设时导出给 spawned core，env wins）；reranker 至今无 Go config 文件侧桥接；既有 setVectorEnv / setRemoteEnv / setDataDirEnv 为跨进程 env-bridge 范式
    When  新增 RerankerConfig（Enabled/Provider/Endpoint/Model，encodeTOML/decodeTOML round-trip 保真，无 api-key 字段）；新 setRerankerEnv helper 在 [reranker] 段存在且对应 env 未设时导出 CONTEXTFORGE_RERANKER_ENDPOINT/_MODEL/_PROVIDER 给 spawned core daemon，接线进 doServe + doMCP（镜像 setRemoteEnv）；spawned core 经既有 select_reranker env 路径接收；显式 env 覆盖 config 文件（env wins）；setRerankerEnv 不处理密钥
    Then  Go config round-trip 含 [reranker] 段 Enabled/Provider/Endpoint/Model 保真（add-only，absent [reranker] ⇒ 零值）+ setRerankerEnv 在 [reranker] 段存在时导出 _ENDPOINT/_MODEL/_PROVIDER、env 已设时不覆盖（ENV WINS，向后兼容）+ 无 [reranker] 段 → 不导出 → 默认行为不变 + API KEY 永不进 config.toml（setRerankerEnv 不处理密钥，CONTEXTFORGE_RERANKER_API_KEY 仅由用户设 env，PRD 安全红线，RerankerConfig 无 api-key 字段）+ Rust core 0 toml dep（复用既有 CONTEXTFORGE_RERANKER_* env 读取）+ 0 NEW dep（TEST-38.2.1 config round-trip + TEST-38.2.2 setRerankerEnv 单测为真实 RED→GREEN）

  # ---
  # Maps to: docs/specs/tasks/task-38.2-reranker-config-bridge-and-data-plane-wiring.md (TEST-38.2.3)
  Scenario: SCEN-38.2.3 — 对应 AC4（Rust 数据面 reranker opt-in 接线：CONTEXTFORGE_RERANKER_PROVIDER=identity → provenance marker / unset → 无 marker 向后兼容字节等价无 rerank）
    Given reranker 至今从未由 config 在生产数据面路径接线（server.rs hybrid:334 + semantic:376 + data_plane/search.rs semantic:282 三处只调 with_embedder().with_vector_searcher()、从不调 with_reranker()，reranker 仅 Phase 21 opt-in builder seam 仅测试用）；新 reranker_from_env() 读 CONTEXTFORGE_RERANKER_PROVIDER → 非空 / 非 none 时 select_reranker → with_reranker；IdentityReranker 的 IDENTITY_RERANK_REASON provenance marker 为可断言信号
    When  数据面三处生产路径经 reranker_from_env() opt-in 接线 with_reranker；设 CONTEXTFORGE_RERANKER_PROVIDER=identity 跑 search_semantic；再 unset CONTEXTFORGE_RERANKER_PROVIDER 跑同一 search_semantic
    Then  CONTEXTFORGE_RERANKER_PROVIDER=identity → search_semantic 结果带 IdentityReranker 的 provenance marker（IDENTITY_RERANK_REASON）+ CONTEXTFORGE_RERANKER_PROVIDER unset → 无 reranker provenance marker、向后兼容字节等价无 rerank（当前行为不变，ADR-004/008——这正是为何「只加 Go [reranker] config 桥而数据面不消费」不诚实，故 task-38.2 端到端：Go 桥 + Rust 数据面消费）+ 0 proto / 0 schema migration / 0 NEW dep（TEST-38.2.3，identity provider 即可 deterministic 断言、不打真实网络）

  # ---
  # Maps to: docs/specs/phases/phase-38-embedding-remote-reranker-live.md §2 + docs/decisions/adr-043-embedding-remote-reranker-live.md (D1/D4)
  Scenario: SCEN-38.ALT — alternatives 据实记录（A1 contract-only-no-live REJECTED / A2 large-benchmark-quality-claim DEFERRED / A3 config-bridge-without-data-plane-wiring REJECTED / A4 api-key-in-config REJECTED，ADR-013 + PRD 安全诚实价值）
    Given 备选 A1 仅 build_rerank_request_body/parse_rerank_response 纯函数契约测试无 live rerank（即此前状态——RemoteRerankerProvider 从未构建、从未对真实端点测过 rerank 质量，不兑现 [SPEC-DEFER:phase-future.embedding-remote-reranker-live]）/ A2 对大语料 / 公开基准做 NDCG/MRR rerank 质量断言（需更大标注集 + 更重 CI、非作者小集 identity 可控对照）/ A3 仅加 Go [reranker] config 桥而 Rust 数据面不消费（config 写了却无生产路径接线，不诚实）/ A4 把 API key 写进 config.toml 便于配置（违 PRD 安全基线）
    When  对四 alternative 据实定夺并记于 phase spec §2、ADR-043 Alternatives：A1 / A3 / A4 REJECTED，A2 因作者小型手工标注 query×candidate 集的 real-vs-identity 对照更干净（可控、可复审、近义干扰显式）作主指标而 DEFERRED
    Then  A1 contract-only-no-live REJECTED（RemoteRerankerProvider 从未构建、从未对真实端点测 rerank 质量，不兑现 defer，ADR-013）+ A2 large-benchmark-quality-claim DEFERRED [SPEC-DEFER:phase-future.reranker-large-corpus-quality]（需更大基准 NDCG/MRR；作者小集 real-vs-identity 对照为更干净主指标，证 real cross-encoder 把明显相关文档排在近义干扰之上、非大基准质量断言）+ A3 config-bridge-without-data-plane-wiring REJECTED（task-38.2 端到端：Go [reranker] 桥 + Rust reranker_from_env() 数据面 opt-in 接线消费）+ A4 api-key-in-config REJECTED（API key 仅由用户设 env、永不进 config，RerankerConfig 无 api-key 字段，PRD 安全红线）+ CI 跑 live remote rerank 复用既有 [SPEC-DEFER:phase-future.embedding-remote-ci-credential]（remote 付费 API 无免费 service container，reranker 同理）+ 多 provider rerank live 续 [SPEC-DEFER:phase-future.embedding-multi-provider-live]（SCEN-38.ALT 据实记录，不伪造数值，真实 closeout 后回填）

  # ---
  # Maps to: docs/specs/tasks/task-38.3-closeout-v0.31.0.md (TEST-38.3.1)
  Scenario: SCEN-38.3.1 — 对应 AC5（默认 0-network / reranker-remote opt-in baseline + 行为不变 + v0.31.0 closeout + [SPEC-DEFER:phase-future.embedding-remote-reranker-live] fulfilled）
    Given task-38.1 + task-38.2 全 Done（RemoteRerankerProvider + select_reranker 工厂 + env-gated remote reranker live harness 度量 real vs identity MRR / recall@1 + Go [reranker] round-trip + setRerankerEnv env-bridge + Rust 数据面 reranker_from_env() opt-in 接线），current Phase 37 smoke v27[46/46]；ADR-043 据 D1-D4 须逐 D Proposed→Accepted（D1 live rerank harness 方法学：real cross-encoder vs IdentityReranker no-semantic-signal 基线对照 + 作者标注 query×candidate 集诚实范围 + env-gated honest-defer + 小集 caveat + 大语料续 defer；D2 真实测得 MRR/recall@1 placeholder 待回填 until 主 agent 本机已认证 SiliconFlow run，ADR-013 不伪造，CI honest-defer 因 remote 付费外部 API 无免费 service container 复用 embedding-remote-ci-credential；D3 reranker-config-bridge + data-plane-wiring：Go [reranker] round-trip + setRerankerEnv env-bridge env-wins、API key env-only 永不进 config、Rust 数据面 reranker_from_env() 三处 opt-in 接线、Rust core 0 toml dep；D4 默认 0-network baseline + 行为不变，reranker-remote opt-in、CONTEXTFORGE_RERANKER_PROVIDER unset 字节等价无 rerank，ADR-004/008，0 NEW dep）
    When  跑 scripts/console_smoke.sh banner v27→v28 + 新增 step → [47/47]（staging dir cf-v30-cfg、offset +2，smoke_syntax_test.go TestTask383 镜像 TestTask373，no-regression [37/37]..[46/46] 不溯改 ADR-014 D5，bash -n 校验），产出 v0.31.0 release docs（docs/releases/v0.31.0-evidence.md + v0.31.0-artifacts.md + README v0.31 段 + RELEASE_NOTES v0.31.0 段，真实 MRR/recall 数 + 诚实记 CI honest-defer，tag/run/digest/tlog 为 [SPEC-DEFER:phase-future.release-backfill] markers 待 post-tag-push），ADR-043 逐 D Proposed→Accepted（per-D ratify with real numbers）+ ADR-026 reranker-provider add-only Phase-38 Amendment（标记 remote reranker 真实联调 + 真实 rerank 质量兑现，不溯改 ADR-026 D-body ADR-014 D5）+ ADR-042 add-only Phase-38 Amendment（标其 embedding-remote-reranker-live follow-up fulfilled）+ roadmap §3.20/§4 add-only + s2v-adapter add-only + phase §6 闭合
    Then  默认行为 / proto / 既有契约不变（ADR-004——reranker-remote opt-in、默认构建 0-network、CONTEXTFORGE_RERANKER_PROVIDER unset 字节等价无 rerank、0 NEW dep、0 schema migration、0 proto，ADR-004/008 既有契约不变）+ smoke v28[47/47]（既有 step 不退化，denominators [37/37]..[46/46] 不溯改 ADR-014 D5）+ ADR-043 逐 D 如实 ratify（D2 真实 MRR/recall 数据据实回填、标注为主 agent 本机已认证 SiliconFlow run、CI honest-defer 诚实记于无免费 service container 复用 embedding-remote-ci-credential）+ [SPEC-DEFER:phase-future.embedding-remote-reranker-live] fulfilled（live remote rerank 已测 + env-gated harness 守护 + 生产数据面 opt-in 接通）+ ADR-014 D1-D5 第二十九次激活全通过（TEST-38.3.1 + 各 task LAST TEST TEST-38.1.3 / TEST-38.2.4 / TEST-38.3.2 = `bash scripts/spec_drift_lint.sh --touched origin/master` 0 unannotated hits，真实跑出后回填）
