# language: en
# Maps to:
#   - docs/specs/phases/phase-37-embedding-provider-remote-live.md
#   - docs/specs/tasks/task-37.1-remote-embedding-live-recall-harness.md
#   - docs/specs/tasks/task-37.2-remote-embedding-config-bridge.md
#   - docs/specs/tasks/task-37.3-closeout-v0.30.0.md
#
# 轻量 BDD（s2v §9.2）；Phase 37 embedding-provider-remote-live（兑现 [SPEC-DEFER:phase-future.embedding-provider-remote]——首次对真实远程 embedding 端点做端到端联调 + 实测语义召回。在此之前仓库只有 deterministic 缺省 provider + feature-gated fastembed；remote 的 build_request_body/parse_response 已是纯函数契约层，从未对 live 端点测过真实召回。ADR-013 诚实优先：本机真实 run 实测数仅在 task-37.1 §10 与 ADR-042 D2 引用且标注为主 agent 本机真实 run，绝不预填）。Scenario ID 在各 task spec §7 追踪表映射到测试 / 真实 run。
# Status: Draft（规划稿，本文件随 phase/task spec 一并 Draft）。
# 默认构建不变：embedding-remote 为 opt-in，默认构建 0-network / deterministic model-free 缺省 provider（ADR-004/008）；0 NEW dep（ureq 自 task-22.3 已 optional）；0 schema migration；0 默认行为变更。harness 复用既有 factory.rs 的 CONTEXTFORGE_REMOTE_* env 读取路径（CONTEXTFORGE_REMOTE_ENDPOINT/_MODEL/_PROVIDER + 仅由用户设 env 的 CONTEXTFORGE_REMOTE_API_KEY，api_key 永不记录 / 永不进 config）。
# 受阻 / 据实非问题维度均以 [SPEC-DEFER:phase-future.<name>] 标注（无 API key 时 honest-defer 干净 skip 不 fail；大语料语义质量需更大基准延后；多 provider 生产化延后），据真实本机已认证 run 回填，绝不预填 release 数值（ADR-013，placeholder 待回填 / floor-only）。

Feature: phase-37-embedding-provider-remote-live
  In order to 把 RemoteEmbeddingProvider（其 build_request_body/parse_response 纯函数构造已实现、ureq → parse_response 路径已在 Windows MSVC --features embedding-remote 真实编译并跑通返回 1024 维向量）的真实端到端联调 + 实测语义召回从 [SPEC-DEFER:phase-future.embedding-provider-remote] 的 honest-defer 状态转为「真实测得 + env-gated harness 守护」（leader 已 DE-RISK 证明：SiliconFlow https://api.siliconflow.cn/v1/embeddings OpenAI-compatible 端点 + Qwen/Qwen3-Embedding-8B 端到端 round-trip 跑通，native dim=4096 且 OpenAI 风格 dimensions 参数被接受并生效——MRL，本 phase 用 1024——CJK 输入正常）
  As Phase 37 内核（env-gated remote embedding live recall harness 在同一作者标注语义集 + 同一 BruteForceVectorBackend 精确余弦路径上度量 real remote 模型 vs deterministic model-free 基线的 recall@1 / recall@3 + Go [remote] Model add-only + setRemoteEnv env-bridge + v0.30.0 closeout）
  I want 新增 core/tests/remote_embedding_recall.rs（#![cfg(feature = "embedding-remote")]，env-gated on CONTEXTFORGE_REMOTE_API_KEY，factory 另读 CONTEXTFORGE_REMOTE_ENDPOINT/_MODEL/_PROVIDER），用作者手工标注的语义集（15 个 case / 16 个文档，覆盖 英文复述 / 代码概念 / CJK / 跨语言，且故意埋近义干扰项 config_save vs config_load、bm25 vs hybrid、cjk_index vs cjk_vector 使 top-k 命中非词面 trivial），把真实 remote 模型与 deterministic（model-free）基线的 embedding 同时索引进同一 BruteForceVectorBackend（0-dep exact cosine），对每个标注 query 取 top-k，recall@1 / recall@3 = mean(命中 relevant id)，先 eprintln 真实测得数再 assert（floor recall@3 >= 0.70 且 remote recall@1 > deterministic recall@1，guard）；当 CONTEXTFORGE_REMOTE_API_KEY 未设时 eprintln 一条 skip 提示并 return（honest-defer，CI 无密钥干净 skip 而非 fail，api_key 永不记录）；另有一个非网络 well-formed 守护测试（doc id 唯一 / 每个 relevant id 存在 / case 数 >= 12）无 key 也总是跑；Go internal/config/config.go 的 RemoteProviderConfig add-only 补 Model 字段（toml round-trip 保真）+ 新 setRemoteEnv helper 镜像 setVectorEnv / setDataDirEnv 跨进程 env-bridge（[remote] 段存在且对应 env 未设时导出 CONTEXTFORGE_REMOTE_ENDPOINT/_MODEL/_PROVIDER 给 spawned core，ENV WINS，无 [remote] 段 → 不导出 → 默认行为不变，API KEY 永不进 config）接线进 doServe + doMCP，且默认构建仍 0 NEW dep / 0-network / deterministic model-free 缺省 / 0 schema migration / 默认行为不变（ADR-004/008——embedding-remote opt-in、ureq 自 task-22.3 已 optional、Rust core 0 toml dep 复用既有 factory env 路径），harness 度量为作者小型手工标注集（大语料语义质量需更大基准，作为更干净主指标外的延后项 [SPEC-DEFER:phase-future.embedding-large-corpus-recall]）

  # ---
  # Maps to: docs/specs/tasks/task-37.1-remote-embedding-live-recall-harness.md (TEST-37.1.1)
  Scenario: SCEN-37.1.1 — 对应 AC1（remote embedding live recall harness 在同一标注集 + 同一 BruteForce exact cosine 上度量 real vs deterministic recall@1 / recall@3 >= floor + remote > deterministic + eprintln 真实数）
    Given core/tests/remote_embedding_recall.rs 以 #![cfg(feature = "embedding-remote")] 门控、env-gated on CONTEXTFORGE_REMOTE_API_KEY（factory 另读 CONTEXTFORGE_REMOTE_ENDPOINT/_MODEL/_PROVIDER，api_key 永不记录）；当 CONTEXTFORGE_REMOTE_API_KEY 已设时一个真实远程 embedding 端点可达；leader 的 DE-RISK 已证明 SiliconFlow OpenAI-compatible 端点 + Qwen/Qwen3-Embedding-8B 端到端 round-trip 跑通（native dim=4096、OpenAI 风格 dimensions=1024 被接受并生效、CJK 输入正常）；BruteForceVectorBackend 为 0-dep exact cosine baseline，real remote 与 deterministic 基线在同一 backend 上索引同一作者标注语义集
    When  用作者手工标注语义集（15 个 case / 16 个文档，覆盖 英文复述 / 代码概念 / CJK / 跨语言，故意埋近义干扰项 config_save vs config_load、bm25 vs hybrid、cjk_index vs cjk_vector），把 real remote 模型 vs deterministic（model-free）基线分别经 select_provider("remote",1024) / 缺省 provider 算 embedding 并 index 进同一 BruteForceVectorBackend，对每个标注 query 取 top-k，算 recall@1 / recall@3 = mean(命中 relevant id)
    Then  先 eprintln 真实测得 real / deterministic recall@1 / recall@3 再 assert：floor recall@3 >= 0.70（guard）且 remote recall@1 > deterministic recall@1（real 模型把明显语义对排在近义干扰之上）+ 真实测得数在 task-37.1 §10 与 ADR-042 D2 据实记录并标注为主 agent 本机真实 SiliconFlow run（floor-only 不预填，ADR-013 不伪造）+ 0 NEW dep / 0 schema migration / 0 默认构建变更（TEST-37.1.1，env-gated，对 live remote 端点真实测试通过后回填真实数）

  # ---
  # Maps to: docs/specs/tasks/task-37.1-remote-embedding-live-recall-harness.md (TEST-37.1.2)
  Scenario: SCEN-37.1.2 — 对应 AC2（无 API key 时 honest-defer 干净 skip 不 fail + 非网络 well-formed 标注集守护测试无 key 也总是跑，api_key 永不记录）
    Given 本地 / CI 无 CONTEXTFORGE_REMOTE_API_KEY 时 harness 无远程端点可达（CI 无密钥）；作者标注语义集（doc id / relevant id / case 数）不依赖任何网络；api_key 仅由用户设 env、永不记录 / 永不进 config（PRD 安全基线）
    When  harness 在 CONTEXTFORGE_REMOTE_API_KEY 未设时 eprintln 一条 skip 提示并 return（honest-defer，不 fail test）；并在无 key 路径下跑非网络 well-formed 守护测试，校验标注集 doc id 唯一 / 每个 relevant id 存在于文档集 / case 数 >= 12
    Then  无 key → live recall harness 干净 skip（eprintln 提示，return，NOT fail；CI/本地无密钥不红，honest-defer 非伪绿）+ 非网络 well-formed 守护测试无 key 也总是跑且通过（doc id 唯一 / 每个 relevant id 存在 / case 数 >= 12，behavior-lock guard）+ api_key 永不出现在任何日志 / 输出（PRD 安全基线）+ 0 NEW dep（TEST-37.1.2，无 key 即可跑，well-formed 守护为真实 RED→GREEN）

  # ---
  # Maps to: docs/specs/tasks/task-37.2-remote-embedding-config-bridge.md (TEST-37.2.1)
  Scenario: SCEN-37.2.1 — 对应 AC3（Go [remote] Model add-only + setRemoteEnv env-bridge env-wins，API key 永不进 config，Rust 0-dep 复用既有 factory env 路径）
    Given factory.rs:52 注释记 "config plumbing is a follow-up"（remote endpoint/model/provider 经既有 CONTEXTFORGE_REMOTE_* env 读取已实现，但 Go config 文件侧无桥接）；internal/config/config.go 的 RemoteProviderConfig 现有 Enabled/Provider/Endpoint；既有 setVectorEnv / setDataDirEnv 为跨进程 env-bridge 范式（[vector] / data-dir 段存在且 env 未设时导出给 spawned core，env wins）
    When  RemoteProviderConfig add-only 补 Model 字段（encodeTOML/decodeTOML round-trip 保真）；新 setRemoteEnv helper 在 [remote] 段存在且对应 env 未设时导出 CONTEXTFORGE_REMOTE_ENDPOINT/_MODEL/_PROVIDER 给 spawned core daemon，接线进 doServe + doMCP（镜像 setVectorEnv）；spawned core 经既有 factory.rs env 路径接收；显式 env 覆盖 config 文件（env wins）；setRemoteEnv 不处理密钥
    Then  Go config round-trip 含 Model 字段保真（add-only，absent [remote] Model ⇒ 零值）+ setRemoteEnv 在 [remote] 段存在时导出 _ENDPOINT/_MODEL/_PROVIDER、env 已设时不覆盖（ENV WINS，向后兼容）+ 无 [remote] 段 → 不导出 → 默认行为不变 + API KEY 永不进 config.toml（setRemoteEnv 不处理密钥，CONTEXTFORGE_REMOTE_API_KEY 仅由用户设 env，PRD 安全红线）+ Rust core 0 toml dep（复用既有 CONTEXTFORGE_REMOTE_* env 读取、0 改动 factory）+ 0 NEW dep（TEST-37.2.1，Go config round-trip + setRemoteEnv 单测为真实 RED→GREEN）

  # ---
  # Maps to: docs/specs/phases/phase-37-embedding-provider-remote-live.md §2 + docs/decisions/adr-042-embedding-provider-remote-live.md (D1/D4)
  Scenario: SCEN-37.ALT — alternatives 据实记录（A1 contract-only-no-live REJECTED / A2 large-benchmark-quality-claim DEFERRED / A3 api-key-in-config REJECTED，ADR-013 + PRD 安全诚实价值）
    Given 备选 A1 仅 build_request_body/parse_response 纯函数契约测试无 live 召回（即此前状态——从未对真实端点测过召回，不兑现 [SPEC-DEFER:phase-future.embedding-provider-remote]）/ A2 对大语料 / 公开基准做语义质量断言（需更大标注集 + 更重 CI、非作者小集 model-free 可控对照）/ A3 把 API key 写进 config.toml 便于配置（违 PRD 安全基线）
    When  对三 alternative 据实定夺并记于 phase spec §2、ADR-042 Alternatives：A1 / A3 REJECTED，A2 因作者小型手工标注集的 real-vs-deterministic 对照更干净（可控、可复审、近义干扰显式）作主指标而 DEFERRED
    Then  A1 contract-only-no-live REJECTED（从未对真实端点测召回，不兑现 defer，ADR-013）+ A2 large-benchmark-quality-claim DEFERRED [SPEC-DEFER:phase-future.embedding-large-corpus-recall]（需更大基准；作者小集 real-vs-deterministic 对照为更干净主指标，recall@3=1.0 仅证模型把明显语义对排在近义干扰之上、非大基准质量断言）+ A3 api-key-in-config REJECTED（API key 仅由用户设 env、永不进 config，PRD 安全红线）+ 多 provider 生产化延后 [SPEC-DEFER:phase-future.embedding-multi-provider-live]（SCEN-37.ALT 据实记录，不伪造数值，真实 closeout 后回填）

  # ---
  # Maps to: docs/specs/tasks/task-37.3-closeout-v0.30.0.md (TEST-37.3.1)
  Scenario: SCEN-37.3.1 — 对应 AC4（默认 0-network / deterministic model-free baseline + 行为不变 + v0.30.0 closeout + [SPEC-DEFER:phase-future.embedding-provider-remote] fulfilled）
    Given task-37.1 + task-37.2 全 Done（env-gated remote embedding live recall harness 度量 real vs deterministic recall@1 / recall@3 + Go [remote] Model add-only + setRemoteEnv env-bridge），current Phase 36 smoke v26[45/45]；ADR-042 据 D1-D4 须逐 D Proposed→Accepted（D1 live recall harness 方法学：real vs deterministic 基线对照 + 作者标注集诚实范围 + env-gated honest-defer + 小集 caveat + 大语料续 defer；D2 真实测得召回数 placeholder 待回填 until 主 agent 本机已认证 SiliconFlow run，ADR-013 不伪造，CI honest-defer 因 remote 是付费外部 API 无免费 service container——与 qdrant 有免费 OSS service container 的诚实差异；D3 remote-embedding-config-bridge：Go [remote] Model add-only + setRemoteEnv env-bridge、env-wins、API key env-only 永不进 config、Rust 0-dep；D4 默认 0-network baseline + 行为不变，embedding-remote opt-in，ADR-004/008，0 NEW dep）
    When  跑 scripts/console_smoke.sh banner v26→v27 + 新增 step → [46/46]（staging dir cf-v29-cfg、offset +2，smoke_syntax_test.go TestTask373 镜像 TestTask363，no-regression [37/37]..[45/45] 不溯改 ADR-014 D5，bash -n 校验），产出 v0.30.0 release docs（docs/releases/v0.30.0-evidence.md + v0.30.0-artifacts.md + README v0.30 段 + RELEASE_NOTES v0.30.0 段，真实 recall 数 + 诚实记 CI honest-defer，tag/run/digest/tlog 为 [SPEC-DEFER:phase-future.release-backfill] markers 待 post-tag-push），ADR-042 逐 D Proposed→Accepted（per-D ratify with real numbers）+ ADR-027 embedding-provider-abstraction add-only Phase-37 Amendment（标记 embedding-provider-remote 真实联调 + 真实召回兑现，不溯改 ADR-027 D-body ADR-014 D5）+ roadmap §3.19/§4 add-only + s2v-adapter add-only + phase §6 闭合
    Then  默认行为 / proto / 既有契约不变（ADR-004——embedding-remote opt-in、默认构建 0-network / deterministic model-free 缺省 provider、0 NEW dep、0 schema migration，ADR-004/008 既有契约不变）+ smoke v27[46/46]（既有 step 不退化，denominators [37/37]..[45/45] 不溯改 ADR-014 D5）+ ADR-042 逐 D 如实 ratify（D2 真实召回数据据实回填、标注为主 agent 本机已认证 SiliconFlow run、CI honest-defer 诚实记于无免费 service container）+ [SPEC-DEFER:phase-future.embedding-provider-remote] fulfilled（live remote 召回已测 + env-gated harness 守护）+ ADR-014 D1-D5 第 28 次激活全通过（TEST-37.3.1 + 各 task LAST TEST TEST-37.1.3 / TEST-37.2.2 / TEST-37.3.2 = `bash scripts/spec_drift_lint.sh --touched origin/master` 0 unannotated hits，真实跑出后回填）
