# language: en
# Maps to:
#   - docs/specs/phases/phase-39-console-api-retrieval-signal-forward.md
#   - docs/specs/tasks/task-39.1-console-dataplane-hybrid-proto-and-dispatch.md
#   - docs/specs/tasks/task-39.2-console-api-hybrid-forward-and-rerank-visibility.md
#   - docs/specs/tasks/task-39.3-closeout-v0.32.0.md
#
# 轻量 BDD（s2v §9.2）；Phase 39 console-api-retrieval-signal-forward（兑现 [SPEC-DEFER:phase-future.console-api-hybrid-forward]——把已存在于检索内核但对外 console-api REST 不可达/不可见的两个信号（hybrid BM25+vector RRF 融合 + rerank reason provenance）经 console_data_plane proto add-only + 数据面 hybrid dispatch + Go console-api 转发首次贯通到对外 POST /v1/search。在此之前 hybrid 信号无法抵达 core（console_data_plane.proto SearchRequest 无 hybrid 字段、data_plane/search.rs query() 无 hybrid dispatch 分支只有 semantic/BM25、contractv1.SearchRequest 无 Hybrid、handleSearch 无 ?hybrid 解析、grpcclient 不转发），rerank reason 虽端到端流通却从未有 smoke/测试断言其在对外 REST 可见。0 backend 算法改动「贯通而非重写」：复用 server.rs hybrid 路径（task-21.1 search_hybrid + req.hybrid + hybrid_score）+ reranker_from_env 数据面 opt-in（task-38.2）+ ?semantic 转发范式（task-20.1）+ vector_score=16 add-only provenance 范式（task-32.3）。诚实校正（ADR-013）：?rerank=true per-request 与 Phase 38 ADR-043 D3 env 驱动模型冲突 → 记为 superseded、不实现，改交付 rerank provenance 可见性）。Scenario ID 在各 task spec §7 追踪表映射到测试。
# Status: Draft（规划稿，本文件随 phase/task spec 一并 Draft）。
# 默认构建不变：hybrid 默认 false → 既有 semantic / BM25 路径字节等价（向后兼容）；reranker 默认 CONTEXTFORGE_RERANKER_PROVIDER unset → 字节等价无 rerank（ADR-043 D3 不变）；proto add-only 新字段 SearchRequest.hybrid=8 / SearchResultItem.hybrid_score=17 既有字段号 1-7 / 1-16 全冻结（ADR-015 D1 add-only，既有 client 兼容）；0 新 dep（复用 search_hybrid / reranker_from_env / with_reranker / 手写 Go 转发 + buf 既有工具链，ADR-008）；0 schema migration。console 数据面 hybrid 分支用 hardcoded BruteForceVectorBackend（镜像数据面既有 semantic 分支，env-factory backend 接入 console 数据面是既有 asymmetry，续 [SPEC-DEFER:phase-future.console-data-plane-vector-backend-factory]）。
# 受阻 / 据实重界定维度均以 [SPEC-DEFER:phase-future.<name>] / superseded 标注（?rerank=true per-request 据 ADR-044 D3 superseded by ADR-043 D3 env 驱动、不实现——改交付 rerank provenance 可见性；console 数据面 env-factory backend 续延后；大语料 hybrid/rerank 对外 REST 召回质量基准续 vector-large-corpus-perf——本 phase 为信号贯通 + provenance 可见性 wiring 断言，hybrid 融合质量 ADR-025 已 ratify、rerank 质量 ADR-043 已 ratify 不重测）；真实 release tag/run/digest 待 post-tag-push 回填，绝不预填（ADR-013，<backfill> marker）。

Feature: phase-39-console-api-retrieval-signal-forward
  In order to 把 hybrid 融合（ADR-025 已在 core 层落地 server.rs hybrid 路径 + search_hybrid + req.hybrid + hybrid_score，但对外 console-api REST 不可达）+ rerank reason provenance（ADR-043 D3 已在生产数据面 opt-in 接线，但对外 REST 可见性从未被断言）从 [SPEC-DEFER:phase-future.console-api-hybrid-forward] 与 [SPEC-DEFER:phase-future.console-api-rerank-forward] 的 honest-defer 状态推进为「对外 POST /v1/search 首次贯通 hybrid 请求 + rerank provenance 可见」（承 Phase 20 console-api ?semantic 贯通范式 + Phase 21 hybrid 融合 + Phase 38 reranker 数据面接线血脉）
  As Phase 39 内核（console_data_plane proto add-only SearchRequest.hybrid=8 + SearchResultItem.hybrid_score=17 + buf generate + data_plane/search.rs query() hybrid dispatch 分支镜像 server.rs hybrid 路径 + Go contractv1 add-only Hybrid/HybridScore + handleSearch ?hybrid OR-merge + grpcclient 转发/映射 + rerank reason provenance 对外 REST 可见 + v0.32.0 closeout）
  I want console_data_plane.proto 的 SearchRequest 加 bool hybrid = 8（紧随 semantic = 7，镜像 v1/search.proto:28）+ SearchResultItem 加 float hybrid_score = 17（紧随 vector_score = 16，镜像 v1 RetrievalResult.hybrid_score=15，parity with v1），既有字段号 1-7 / 1-16 全冻结（ADR-015 D1 add-only）；buf generate 重生 Go + Rust stub；core/src/data_plane/search.rs 的 query() 把 let hits = if req.semantic {..} else {BM25}（:282-315）改为 if req.hybrid {..} else if req.semantic {..} else {BM25}，hybrid 分支镜像 server.rs hybrid 路径（:328-376）+ 数据面自身 semantic 分支结构（model-free DeterministicEmbeddingProvider::default() + 0-dep BruteForceVectorBackend::new() + enumerate_chunks + index_chunks_semantic + search_hybrid(&req.query, top_k) + 复用 reranker_from_env() opt-in 同 semantic 分支 :291-295），命中 retrieval_method 由 search_hybrid 标 "hybrid"；结果映射（:339-368）加 hybrid_score: if h.retrieval_method == "hybrid" { h.score } else { 0.0 }（镜像 vector_score 条件 :359-363，融合分端到端携带非由 score 推断 ADR-013）；Go internal/contractv1/contractv1.go 的 SearchRequest 加 Hybrid bool（json hybrid，镜像 Semantic :125 add-only opt-in）+ SearchResult 加 HybridScore float32（json hybrid_score，镜像 VectorScore :153 cross-repo add-only provenance ADR-014 D4）；internal/consoleapi/handlers.go 的 handleSearch（:443-462）加 if r.URL.Query().Get("hybrid") == "true" { body.Hybrid = true }（镜像 ?semantic :452-454）；internal/consoleapi/grpcclient/grpcclient.go 的 Search（:364-390）加 Hybrid: req.Hybrid（镜像 Semantic :372）+ protoToSearchResult（:609-643）加 HybridScore: p.HybridScore（镜像 VectorScore :623），rerank reason 经既有 Reason: p.Reason（:624）链路对外 REST 可见；对外 POST /v1/search（body {"hybrid":true} 或 ?hybrid=true）贯通到 core hybrid 路径、响应携 retrieval_method="hybrid" + hybrid_score + （reranker env opt-in 时）reason rerank marker；reranker 保持 env 驱动（CONTEXTFORGE_RERANKER_PROVIDER，ADR-043 D3 不变，本 phase 不加 ?rerank 参数——per-request 与 env 驱动冲突据 ADR-044 D3 superseded）；且默认 hybrid=false → 走既有 semantic / BM25 分支字节等价 + reranker unset → 无 rerank 字节等价 + proto add-only 既有字段号冻结 + 0 新 dep / 0 schema migration（ADR-004/008/015 既有契约不变）

  # ---
  # Maps to: docs/specs/tasks/task-39.1-console-dataplane-hybrid-proto-and-dispatch.md (TEST-39.1.1 / TEST-39.1.2)
  Scenario: SCEN-39.1.1 — 对应 AC1（console_data_plane proto add-only SearchRequest.hybrid=8 + SearchResultItem.hybrid_score=17 既有字段号冻结 + 数据面 hybrid dispatch 镜像 server.rs hybrid 路径 + 默认 hybrid=false 字节等价）
    Given proto/contextforge/console_data_plane/v1/console_data_plane.proto 的 SearchRequest 只到 semantic=7（无 hybrid 字段）+ SearchResultItem 只到 vector_score=16（无 hybrid_score 字段）；core/src/data_plane/search.rs 的 query() 只有 let hits = if req.semantic {..} else {BM25}（无 hybrid dispatch 分支）；core/src/server.rs 的 hybrid 路径（:328-376，search_hybrid + req.hybrid + retrieval_method="hybrid" + hybrid_score）+ retriever search_hybrid（task-21.1）+ reranker_from_env（task-38.2）均已存在为范本
    When  SearchRequest add-only bool hybrid = 8（紧随 semantic = 7，镜像 v1/search.proto:28）+ SearchResultItem add-only float hybrid_score = 17（紧随 vector_score = 16，镜像 v1 RetrievalResult.hybrid_score=15），既有字段号 1-7 / 1-16 全冻结；buf generate 重生 Go + Rust stub；query() 改 if req.hybrid {..} else if req.semantic {..} else {BM25}，hybrid 分支镜像 server.rs hybrid 路径 + 数据面 semantic 分支结构（hardcoded DeterministicEmbeddingProvider + BruteForceVectorBackend + search_hybrid + 复用 reranker_from_env opt-in）+ 结果映射 hybrid_score: if h.retrieval_method == "hybrid" { h.score } else { 0.0 }
    Then  SearchRequest.hybrid 字段号 = 8 / SearchResultItem.hybrid_score 字段号 = 17（既有字段号 1-7 / 1-16 不动，ADR-015 D1 既有 client 兼容）+ req.hybrid=true ⇒ query() 走 search_hybrid、命中 retrieval_method="hybrid" + hybrid_score 非零（复用 reranker_from_env opt-in，同 semantic 分支）+ req.hybrid=false + req.semantic=true ⇒ 走 semantic 分支命中 retrieval_method="vector" 字节等价 + 两者皆 false ⇒ BM25 字节等价（默认 hybrid=false 向后兼容，ADR-004）+ hybrid 命中 hybrid_score = h.score（search_hybrid RRF 融合分，端到端携带非推断）/ 非 hybrid 命中 hybrid_score = 0.0（镜像 vector_score 条件，非伪造 ADR-013）+ console 数据面 hybrid 分支用 hardcoded BruteForceVectorBackend（env-factory backend 续 [SPEC-DEFER:phase-future.console-data-plane-vector-backend-factory]）+ 0 新 dep / 0 schema migration（TEST-39.1.1 数据面 hybrid dispatch + TEST-39.1.2 proto add-only + hybrid_score 填充，真实 RED→GREEN）

  # ---
  # Maps to: docs/specs/tasks/task-39.2-console-api-hybrid-forward-and-rerank-visibility.md (TEST-39.2.1 / TEST-39.2.2)
  Scenario: SCEN-39.2.1 — 对应 AC2（Go console-api contractv1 add-only Hybrid/HybridScore + handleSearch ?hybrid OR-merge + grpcclient 转发/映射 + 对外 POST /v1/search 贯通 hybrid + rerank reason provenance 可见 + 默认 hybrid=false 字节等价）
    Given internal/contractv1/contractv1.go 的 SearchRequest 有 Semantic bool（:125，task-20.1）但无 Hybrid + SearchResult 有 VectorScore float32（:153，task-32.3）+ Reason string（:154）但无 HybridScore；internal/consoleapi/handlers.go 的 handleSearch 只 OR-merge ?semantic（:452-454）；internal/consoleapi/grpcclient/grpcclient.go 的 Search 只转发 Semantic（:372）+ protoToSearchResult 只映射 VectorScore（:623）/ Reason（:624）；task-39.1 的 console_data_plane proto hybrid=8 / hybrid_score=17 + 数据面 hybrid dispatch 已就位（buf generate 后 pb.SearchRequest.Hybrid / pb.SearchResultItem.HybridScore 可用）
    When  SearchRequest add-only Hybrid bool（json hybrid，镜像 Semantic）+ SearchResult add-only HybridScore float32（json hybrid_score，镜像 VectorScore）；handleSearch 加 if r.URL.Query().Get("hybrid") == "true" { body.Hybrid = true }（镜像 ?semantic）；Search 加 Hybrid: req.Hybrid（镜像 Semantic）+ protoToSearchResult 加 HybridScore: p.HybridScore（镜像 VectorScore）；对外 POST /v1/search body {"query":"...","hybrid":true} 或 ?hybrid=true；reranker 由 CONTEXTFORGE_RERANKER_PROVIDER env 服务端 opt-in（不加 ?rerank 参数）
    Then  handleSearch ?hybrid=true ⇒ body.Hybrid=true / body {"hybrid":true} ⇒ Hybrid=true / 两者皆无 ⇒ Hybrid=false（默认向后兼容，镜像 ?semantic）+ ?hybrid / ?semantic 独立透传（设 ?hybrid 不影响 Semantic）+ Search 转发 req.Hybrid 到 pb.SearchRequest.Hybrid（默认 false 转发 false 字节等价）+ protoToSearchResult 映射 p.HybridScore 到 out.HybridScore + p.Reason 到 out.Reason（rerank provenance 承载）+ 对外 POST /v1/search hybrid=true ⇒ core hybrid 路径 ⇒ 响应 retrieval_method="hybrid" + hybrid_score + （CONTEXTFORGE_RERANKER_PROVIDER=identity 时）reason 含 rerank marker（rerank provenance 对外 REST 可见）+ reranker 不经 grpcclient 转发（env 驱动，无 ?rerank 字段，ADR-043 D3 / ADR-044 D3）+ 0 新 dep / 0 proto 再改（TEST-39.2.1 handleSearch ?hybrid OR-merge + TEST-39.2.2 grpcclient 转发 + 映射，真实 RED→GREEN）

  # ---
  # Maps to: docs/specs/phases/phase-39-console-api-retrieval-signal-forward.md §2 + docs/decisions/adr-044-console-api-retrieval-signal-forward.md (D3 / Alternatives)
  Scenario: SCEN-39.ALT — alternatives 据实记录（A1 go-forward-only-no-proto REJECTED / A2 rerank-per-request-param REJECTED-superseded / A3 console-dataplane-env-factory-backend DEFERRED / A4 hybrid-score-inferred-not-carried REJECTED，ADR-013 据实分级不矛盾实现）
    Given 备选 A1 仅加 Go console-api ?hybrid 解析而不改 console_data_plane proto / 数据面（hybrid flag 无法抵达 core——proto 无字段、grpcclient 无处转发、数据面无 hybrid 分支，Go 侧解析了也是 no-op）/ A2 实现 ?rerank=true per-request 转发镜像 ?hybrid（与 ADR-043 D3 reranker env 驱动冲突——per-request 覆盖服务端 reranker 选型，破 env 驱动模型 + ADR-004 local-first）/ A3 console 数据面 hybrid 分支用 server.rs 的 env-factory backend 选型而非 hardcoded BruteForceVectorBackend（console 数据面既有 semantic 分支已用 hardcoded backend，task-32.1 env-factory 只接入 server.rs 是既有 asymmetry）/ A4 hybrid_score 由 score + retrieval_method 在 Go 侧推断而非 proto 独立字段（违 v1 parity + score 经 reranker 重排后可能已非 RRF 原始融合分）
    When  对四 alternative 据实定夺并记于 phase spec §2、ADR-044 Alternatives：A1 / A2 / A4 REJECTED，A3 因 console 数据面既有 semantic 分支 hardcoded backend 内部一致性优先而 DEFERRED
    Then  A1 go-forward-only-no-proto REJECTED（hybrid flag 无法抵达 core，转发链路不通则非真实贯通，ADR-013；proto add-only + 数据面 dispatch + Go 转发须端到端）+ A2 rerank-per-request-param REJECTED-superseded（?rerank=true per-request 与 ADR-043 D3 env 驱动冲突，据 ADR-044 D3 记为 superseded、不实现，改交付 rerank provenance 可见性 [SPEC-DEFER:phase-future.console-api-rerank-forward]——据实记录不夸大为已实现 per-request）+ A3 console-dataplane-env-factory-backend DEFERRED [SPEC-DEFER:phase-future.console-data-plane-vector-backend-factory]（hybrid 分支镜像数据面 semantic 分支 hardcoded backend 保内部一致，env-factory backend 接入 console 数据面是既有 asymmetry 统一扩面 follow-up）+ A4 hybrid-score-inferred-not-carried REJECTED（违 v1 parity + ADR-013，hybrid_score=17 add-only 独立字段使融合分端到端忠实携带、非由 score 推断，同 vector_score=16 范式）+ 大语料 hybrid/rerank 对外 REST 召回质量基准续 [SPEC-DEFER:phase-future.vector-large-corpus-perf]（本 phase 为信号贯通 + provenance 可见性 wiring 断言，hybrid 融合质量 ADR-025 已 ratify、rerank 质量 ADR-043 已 ratify 不重测）（SCEN-39.ALT 据实记录，不伪造数值）

  # ---
  # Maps to: docs/specs/tasks/task-39.3-closeout-v0.32.0.md (TEST-39.3.1)
  Scenario: SCEN-39.3.1 — 对应 AC3（默认 hybrid=false / reranker unset 字节等价 baseline + 行为不变 + v0.32.0 closeout + [SPEC-DEFER:phase-future.console-api-hybrid-forward] fulfilled + console-api-rerank-forward 重界定 fulfilled）
    Given task-39.1 + task-39.2 全 Done（console_data_plane proto add-only hybrid=8 / hybrid_score=17 + 数据面 hybrid dispatch + Go contractv1 Hybrid/HybridScore + handleSearch ?hybrid OR-merge + grpcclient 转发/映射 + rerank reason provenance 对外 REST 可见），current Phase 38 smoke v28[47/47]；ADR-044 据 D1-D4 须逐 D Proposed→Accepted（D1 console_data_plane proto add-only + 数据面 hybrid dispatch 既有字段号冻结、镜像 server.rs hybrid 路径、默认 hybrid=false 字节等价；D2 Go console-api hybrid 转发 + rerank provenance 可见性镜像 ?semantic 范式、对外 POST /v1/search 贯通；D3 rerank-forward 重界定——reranker 保持 env 驱动、?rerank per-request superseded by ADR-043 D3、交付 provenance 可见性；D4 默认 hybrid=false / reranker unset 字节等价 + 0 新 dep + proto add-only 既有契约不变 ADR-004/008/015）
    When  跑 scripts/console_smoke.sh banner v28→v29 + 新增 step → [48/48]（staging dir 顺位 offset，端到端断言 ?hybrid=true → retrieval_method="hybrid" / hybrid_score + CONTEXTFORGE_RERANKER_PROVIDER=identity → rerank reason marker 对外 REST 可见，镜像 step [29] 风格；smoke_syntax_test.go TestTask393 镜像 TestTask383，no-regression [37/37]..[47/47] 不溯改 ADR-014 D5，bash -n 校验），产出 v0.32.0 release docs（docs/releases/v0.32.0-evidence.md + v0.32.0-artifacts.md + README v0.32 段替换 :350「in a later release」措辞 + RELEASE_NOTES v0.32.0 段，hybrid 贯通 + rerank provenance 可见证据，tag/run/digest/tlog <backfill> markers 待 post-tag-push），ADR-044 逐 D Proposed→Accepted（per-D ratify）+ ADR-025 add-only Phase-39 Amendment（标 console-api-hybrid-forward fulfilled，不溯改 ADR-025 D-body ADR-014 D5）+ ADR-043 add-only Phase-39 Amendment（标 console-api-rerank-forward 重界定为 provenance 可见性 fulfilled + ?rerank per-request superseded by D3）+ roadmap §3.21/§4 add-only + s2v-adapter add-only + defer marker（console_smoke.sh:49-50 / smoke_syntax_test.go:705-706 / README:350）据实更新 + phase §6 闭合
    Then  默认行为 / proto / 既有契约不变（ADR-004/015——hybrid 默认 false 走既有 semantic / BM25 字节等价、reranker unset 字节等价无 rerank、proto add-only 既有字段号 1-7 / 1-16 冻结、0 新 dep、0 schema migration ADR-008）+ smoke v29[48/48]（既有 step 不退化，denominators [37/37]..[47/47] 不溯改 ADR-014 D5）+ ADR-044 逐 D 如实 ratify + [SPEC-DEFER:phase-future.console-api-hybrid-forward] fulfilled（对外 console-api ?hybrid=true REST 贯通到 core hybrid 路径 + hybrid_score provenance）+ console-api-rerank-forward 据实重界定 fulfilled（rerank reason provenance 对外 REST 可见、reranker 保持 env 驱动、?rerank per-request superseded by ADR-043 D3 不实现）+ tag/run/digest <backfill> 待 post-tag-push 回填不预填（ADR-013）+ ADR-014 D1-D5 第三十次激活全通过（TEST-39.3.1 + 各 task LAST TEST TEST-39.1.3 / TEST-39.2.3 / TEST-39.3.2 = `bash scripts/spec_drift_lint.sh --touched origin/master` 0 unannotated hits，真实跑出后回填）
