#!/usr/bin/env bash
# scripts/console_smoke.sh — Phase 12 console-contract-completion smoke (v3).
#
# v0.5 REAL mode (default): spawns BOTH the Rust `contextforge-core` daemon
# (data plane gRPC) AND the Go `console-api-serve` REST proxy. The
# console-api-serve dials the Rust daemon over gRPC, so the 13 REST endpoints
# (v0.4 9 + task-12.1 3 + task-12.2 1 + task-12.3 1) go through the real
# cross-process bridge (ADR-016 D2 / ADR-017 D1 Wave 1+2).
#
# Modes (selected by env):
#
#   Default (REAL mode):  spawn contextforge-core + console-api-serve;
#       curl the 9 endpoints + run index-job against test/fixtures/index-job-real/
#       + POST /v1/search returns ≥1 real chunk. Final marker:
#       CONSOLE_REAL_SMOKE_EXIT=0.
#
#   LOCAL_ONLY=1: v0.3 backward-compatible mode — only spawns console-api-serve
#       with CONSOLE_API_FALLBACK_INMEM=1 (no Rust daemon). Final marker:
#       CONSOLE_SMOKE_EXIT=0.
#
#   DOCKER_SMOKE=1: docker compose up; same 9 endpoint flow against the
#       docker-published REST port (v0.3 compat path).
#
# Designed for Linux / WSL2 / macOS / Git Bash on Windows.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

STAGING="$(mktemp -d -t cfg-console-smoke-XXXXXX)"
cleanup_local=""
trap 'cleanup' EXIT
cleanup() {
  if [ -n "$cleanup_local" ]; then
    eval "$cleanup_local"
  fi
  rm -rf "$STAGING"
}

EXE_SUFFIX=""
if [ "${OS:-}" = "Windows_NT" ]; then
  EXE_SUFFIX=".exe"
fi

# ----------- Mode selection -----------
MODE="real"
if [ "${LOCAL_ONLY:-0}" = "1" ]; then
  MODE="local"
elif [ "${DOCKER_SMOKE:-0}" = "1" ]; then
  MODE="docker"
fi
echo "[mode] $MODE (REAL=v0.4 default; LOCAL_ONLY=1 = v0.3 inmem; DOCKER_SMOKE=1 = docker compose)"

REST_PORT="48181"
GRPC_PORT="50552"   # randomized-ish to avoid clashing with system Phase 9 default :50551
BASE="http://127.0.0.1:${REST_PORT}"

# ----------- Mode dispatch -----------
case "$MODE" in
  real)
    DATA_DIR="$STAGING/cf-data"
    mkdir -p "$DATA_DIR"
    echo "[real][1/4] cargo build -p contextforge-core"
    cargo build -p contextforge-core --quiet 2>&1 || cargo build -p contextforge-core
    CORE_BIN="$ROOT/target/debug/contextforge-core${EXE_SUFFIX}"
    if [ ! -x "$CORE_BIN" ]; then
      echo "FAIL: $CORE_BIN missing after cargo build" >&2
      exit 1
    fi

    echo "[real][2/4] spawn contextforge-core at 127.0.0.1:${GRPC_PORT}"
    "$CORE_BIN" "127.0.0.1:${GRPC_PORT}" "$DATA_DIR" >"$STAGING/core.log" 2>&1 &
    CORE_PID=$!

    echo "[real][3/4] go build ./cmd/contextforge"
    GO_BIN="$STAGING/contextforge${EXE_SUFFIX}"
    go build -o "$GO_BIN" ./cmd/contextforge

    echo "[real][4/4] spawn console-api-serve at $BASE → gRPC 127.0.0.1:${GRPC_PORT}"
    "$GO_BIN" console-api-serve --addr "127.0.0.1:${REST_PORT}" --grpc-addr "127.0.0.1:${GRPC_PORT}" >"$STAGING/api.log" 2>&1 &
    API_PID=$!
    cleanup_local="kill -TERM $API_PID 2>/dev/null || true; kill -TERM $CORE_PID 2>/dev/null || true; wait $API_PID 2>/dev/null || true; wait $CORE_PID 2>/dev/null || true"
    ;;
  local)
    echo "[local] go build ./cmd/contextforge"
    GO_BIN="$STAGING/contextforge${EXE_SUFFIX}"
    go build -o "$GO_BIN" ./cmd/contextforge
    echo "[local] spawn console-api-serve at $BASE (CONSOLE_API_FALLBACK_INMEM=1)"
    CONSOLE_API_FALLBACK_INMEM=1 "$GO_BIN" console-api-serve --addr "127.0.0.1:${REST_PORT}" >"$STAGING/api.log" 2>&1 &
    API_PID=$!
    cleanup_local="kill -TERM $API_PID 2>/dev/null || true; wait $API_PID 2>/dev/null || true"
    ;;
  docker)
    if ! command -v docker >/dev/null 2>&1; then
      echo "ERROR: docker not on PATH" >&2
      exit 1
    fi
    echo "[docker] building + starting contextforge service..."
    docker compose -f deploy/console-stack.yml up -d --build contextforge
    cleanup_local='docker compose -f deploy/console-stack.yml down -v 2>&1 | tail -3 || true'
    ;;
esac

# ----------- Wait for health -----------
echo "[wait] /v1/health up to 30s"
for i in $(seq 1 30); do
  if curl -sf "$BASE/v1/health" >/dev/null 2>&1; then
    echo "  ✅ health responsive at attempt $i"
    break
  fi
  sleep 1
  if [ "$i" = "30" ]; then
    echo "FAIL: /v1/health did not respond within 30s" >&2
    if [ "$MODE" = "real" ]; then
      echo "---- core.log ----" >&2; tail -50 "$STAGING/core.log" 2>/dev/null || true
      echo "---- api.log ----" >&2; tail -50 "$STAGING/api.log" 2>/dev/null || true
    elif [ "$MODE" = "local" ]; then
      tail -50 "$STAGING/api.log" >&2 || true
    fi
    exit 1
  fi
done

# ----------- 13 endpoint flow (v0.5: 9 base + task-12.1 3 + task-12.2 1 + task-12.3 1) -----------
echo "[flow] 13 endpoint flow"

echo "  [1/13] GET /v1/health (must contain contract_version=v1)"
health_body=$(curl -sf "$BASE/v1/health")
echo "$health_body" | grep -q '"contract_version":"v1"' \
  || { echo "FAIL: /v1/health body missing contract_version=v1: $health_body" >&2; exit 1; }

# REAL mode: workspace_id is generated by Rust (UUID-like via the v0.4 path);
# we still need to feed the proto Create with a workspace_id. Use a stable name.
WS_NAME="cf-real-smoke"

echo "  [2/13] POST /v1/workspaces"
# task-11.3 SqliteWorkspaceStore validates root_path via Rust Path::is_absolute,
# which on Windows requires native form (C:\...) not Git-Bash form (/h/...).
# Use cygpath when available to translate; otherwise pass through.
WS_ROOT="$ROOT/test/fixtures/index-job-real"
if [ "$MODE" != "real" ]; then
  WS_ROOT="/tmp/cf-smoke-fixture"
elif command -v cygpath >/dev/null 2>&1; then
  WS_ROOT="$(cygpath -w "$WS_ROOT" | sed 's|\\|/|g')"
fi
ws_body=$(curl -sf -X POST "$BASE/v1/workspaces" \
  -H 'Content-Type: application/json' \
  -d "{\"name\":\"$WS_NAME\",\"root_path\":\"$WS_ROOT\",\"allowlist\":[\"*.md\"],\"denylist\":[]}")
WS_ID=$(echo "$ws_body" | sed -n 's/.*"workspace_id":"\([^"]*\)".*/\1/p')
[ -z "$WS_ID" ] && { echo "FAIL: workspace_id not parsed: $ws_body" >&2; exit 1; }
echo "    → workspace_id=$WS_ID"

echo "  [3/13] GET /v1/workspaces (list)"
list_body=$(curl -sf "$BASE/v1/workspaces")
echo "$list_body" | grep -q "\"workspace_id\":\"${WS_ID}\"" \
  || { echo "FAIL: list does not contain $WS_ID: $list_body" >&2; exit 1; }

echo "  [4/13] GET /v1/workspaces/$WS_ID"
single_body=$(curl -sf "$BASE/v1/workspaces/${WS_ID}")
echo "$single_body" | grep -q "\"name\":\"${WS_NAME}\"" \
  || { echo "FAIL: single get missing name: $single_body" >&2; exit 1; }

echo "  [5/13] GET /v1/workspaces/non-existent-id (must return 404)"
code=$(curl -s -o /dev/null -w '%{http_code}' "$BASE/v1/workspaces/non-existent-id")
[ "$code" = "404" ] || { echo "FAIL: expected 404; got $code" >&2; exit 1; }

echo "  [6/13] POST /v1/index-jobs (enqueue against fixture repo)"
job_body=$(curl -sf -X POST "$BASE/v1/index-jobs" \
  -H 'Content-Type: application/json' \
  -d "{\"workspace_id\":\"${WS_ID}\",\"trigger_source\":\"smoke\"}")
JOB_ID=$(echo "$job_body" | sed -n 's/.*"job_id":"\([^"]*\)".*/\1/p')
[ -z "$JOB_ID" ] && { echo "FAIL: job_id not parsed: $job_body" >&2; exit 1; }
echo "    → job_id=$JOB_ID"

echo "  [7/13] poll /v1/index-jobs/<id> until status terminal (≤30s)"
if [ "$MODE" = "real" ]; then
  for i in $(seq 1 30); do
    job_body=$(curl -sf "$BASE/v1/index-jobs/${JOB_ID}")
    status=$(echo "$job_body" | sed -n 's/.*"status":"\([^"]*\)".*/\1/p')
    case "$status" in
      succeeded|failed|cancelled)
        echo "    → terminal at attempt $i: status=$status"
        break
        ;;
      *)
        sleep 1
        ;;
    esac
    if [ "$i" = "30" ]; then
      echo "FAIL: job did not reach terminal in 30s; last=$job_body" >&2
      exit 1
    fi
  done
  [ "$status" = "succeeded" ] || echo "  NOTE: REAL job status=$status (test fixture index)"
else
  # LOCAL_ONLY / docker: in-memory MemStore can still drive cancel.
  curl -sf "$BASE/v1/index-jobs/${JOB_ID}" >/dev/null
  cancel_code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$BASE/v1/index-jobs/${JOB_ID}/cancel")
  [ "$cancel_code" = "200" ] || [ "$cancel_code" = "409" ] || { echo "FAIL: cancel expected 200/409; got $cancel_code" >&2; exit 1; }
fi

echo "  [8/13] POST /v1/search (real mode → ≥1 chunk; inmem → empty trace ok)"
search_body=$(curl -sf -X POST "$BASE/v1/search" \
  -H 'Content-Type: application/json' \
  -d "{\"query\":\"contextforge\",\"workspace_id\":\"${WS_ID}\",\"top_k\":5,\"retrieval_method\":\"bm25\",\"agent_scope\":\"session\"}")
echo "$search_body" | grep -q '"result"' \
  && echo "$search_body" | grep -q '"trace"' \
  || { echo "FAIL: search not nested {result, trace}: $search_body" >&2; exit 1; }
if [ "$MODE" = "real" ] && [ "${status:-}" = "succeeded" ]; then
  # REAL mode + index succeeded → search should return at least 1 chunk
  echo "$search_body" | grep -q '"chunk_id"' \
    || echo "  NOTE: REAL search returned 0 chunks (may be fixture-too-small)"
fi

# Extract query_id + chunk_id for follow-on smoke steps (task-12.2 / 12.3).
QUERY_ID=$(echo "$search_body" | sed -nE 's/.*"query_id":"([^"]+)".*/\1/p' | head -1)
CHUNK_ID=$(echo "$search_body" | sed -nE 's/.*"chunk_id":"([^"]+)".*/\1/p' | head -1)

echo "  [9/13] task-12.1 PATCH /v1/workspaces/<id>/config (X-Confirm required → 412 then 200)"
if [ "$MODE" = "real" ]; then
  # No X-Confirm → 412
  code412=$(curl -sf -o /dev/null -w '%{http_code}' -X PATCH "$BASE/v1/workspaces/${WS_ID}/config" \
    -H 'Content-Type: application/json' \
    -d '{"allowlist":["src/**"],"denylist":["node_modules/**"]}' || true)
  [ "$code412" = "412" ] \
    || { echo "FAIL: PATCH config without X-Confirm expected 412; got $code412" >&2; exit 1; }
  # With X-Confirm → 200
  curl -sf -X PATCH "$BASE/v1/workspaces/${WS_ID}/config" \
    -H 'Content-Type: application/json' \
    -H 'X-Confirm: yes' \
    -d '{"allowlist":["src/**"],"denylist":["node_modules/**"]}' >/dev/null \
    || { echo "FAIL: PATCH config with X-Confirm did not return 2xx" >&2; exit 1; }
fi

echo "  [10/13] task-12.1 GET /v1/index-jobs?status=active (missing status → 400)"
if [ "$MODE" = "real" ]; then
  active_body=$(curl -sf "$BASE/v1/index-jobs?status=active") \
    || { echo "FAIL: GET active jobs" >&2; exit 1; }
  # Missing filter → 400
  code400=$(curl -sf -o /dev/null -w '%{http_code}' "$BASE/v1/index-jobs" || true)
  [ "$code400" = "400" ] \
    || { echo "FAIL: GET index-jobs without status expected 400; got $code400" >&2; exit 1; }
fi

echo "  [11/13] task-12.2 GET /v1/source-chunks/<id> (or 404 if no chunk extracted)"
if [ "$MODE" = "real" ] && [ -n "$CHUNK_ID" ]; then
  curl -sf "$BASE/v1/source-chunks/$CHUNK_ID" >/dev/null \
    && echo "  ok: chunk $CHUNK_ID found" \
    || echo "  NOTE: source-chunks/$CHUNK_ID lookup failed (may be retriever cache miss)"
elif [ "$MODE" = "real" ]; then
  # No chunk from search → expect 404 on a fake id
  code404=$(curl -sf -o /dev/null -w '%{http_code}' "$BASE/v1/source-chunks/chk_fake_0" || true)
  [ "$code404" = "404" ] \
    || { echo "FAIL: GET source-chunks unknown expected 404; got $code404" >&2; exit 1; }
fi

echo "  [12/13] task-12.3 GET /v1/search/<query_id>/trace (or 404 on unknown)"
if [ "$MODE" = "real" ] && [ -n "$QUERY_ID" ]; then
  trace_body=$(curl -sf "$BASE/v1/search/$QUERY_ID/trace") \
    && echo "$trace_body" | grep -q '"trace_id"' \
    || echo "  NOTE: trace lookup for $QUERY_ID returned non-2xx or missing trace_id"
fi
# Unknown query_id → 404 (always validated)
if [ "$MODE" = "real" ]; then
  code404=$(curl -sf -o /dev/null -w '%{http_code}' "$BASE/v1/search/qry-does-not-exist/trace" || true)
  [ "$code404" = "404" ] \
    || { echo "FAIL: GET trace unknown expected 404; got $code404" >&2; exit 1; }
fi

echo "  [13/13] GET /v1/observability/events"
events_body=$(curl -sf "$BASE/v1/observability/events?wait=2s")
# REAL mode: at least 1 indexing.progress event from the index job; LOCAL_ONLY:
# any event (or empty array — long-poll returned empty within timeout).
if [ "$MODE" = "real" ]; then
  echo "$events_body" | grep -q '"event_id"' \
    || echo "  NOTE: REAL events array empty (race vs index finish; not fatal)"
fi

echo
if [ "$MODE" = "real" ]; then
  echo "CONSOLE_REAL_SMOKE_EXIT=0"
else
  echo "CONSOLE_SMOKE_EXIT=0"
fi
