//! The measurement runner: drives any `VectorIndexer + VectorSearcher` over a corpus +
//! query set and produces a `MeasureReport` covering the Phase 18 §2A 5 dimensions.

use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

use contextforge_core::retriever::vector::{
    ChunkId, VectorChunk, VectorError, VectorIndexConfig, VectorIndexer, VectorMetric,
    VectorSearcher,
};

use crate::corpus::Query;
use crate::measure::{percentile_ms, recall_rate};
use crate::rss::sample_rss_mb;

/// One backend's 5-dimension measurement result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MeasureReport {
    pub backend_name: String,
    pub n: usize,
    pub dim: usize,
    pub recall_at_5: f64,
    pub recall_at_10: f64,
    pub p95_latency_ms: f64,
    pub idle_rss_mb: Option<f64>,
    pub index_rss_mb: Option<f64>,
    pub cold_start_ms: f64,
    pub reindex_ms: f64,
}

/// Run the full measurement loop against `backend`.
pub fn run<B: VectorIndexer + VectorSearcher>(
    backend: &B,
    corpus: &[VectorChunk],
    queries: &[Query],
    dim: usize,
) -> Result<MeasureReport, VectorError> {
    let idle_rss_mb = sample_rss_mb();

    let cfg = VectorIndexConfig {
        dim,
        metric: VectorMetric::Cosine,
        persistence_path: None,
        collection_id: "spike".to_string(),
    };

    // cold-start: open + first full index build.
    let t0 = Instant::now();
    backend.open(cfg)?;
    backend.index_batch(corpus)?;
    backend.flush()?;
    let cold_start_ms = t0.elapsed().as_secs_f64() * 1000.0;

    let index_rss_mb = sample_rss_mb();

    // reindex: delete all + rebuild from scratch.
    let ids: Vec<ChunkId> = corpus.iter().map(|c| c.chunk_id.clone()).collect();
    let t1 = Instant::now();
    backend.delete(&ids)?;
    backend.index_batch(corpus)?;
    backend.flush()?;
    let reindex_ms = t1.elapsed().as_secs_f64() * 1000.0;

    // queries: per-search latency + top-10 for recall.
    let mut latencies: Vec<Duration> = Vec::with_capacity(queries.len());
    let mut got: Vec<Vec<ChunkId>> = Vec::with_capacity(queries.len());
    for q in queries {
        let t = Instant::now();
        let hits = backend.search(&q.vec, 10, None)?;
        latencies.push(t.elapsed());
        got.push(hits.into_iter().map(|h| h.chunk_id).collect());
    }
    let truths: Vec<ChunkId> = queries.iter().map(|q| q.truth.clone()).collect();
    let recall_at_5 = recall_rate(&got, &truths, 5);
    let recall_at_10 = recall_rate(&got, &truths, 10);
    let p95_latency_ms = percentile_ms(&mut latencies, 0.95);

    let _ = backend.close();

    Ok(MeasureReport {
        backend_name: backend.name().to_string(),
        n: corpus.len(),
        dim,
        recall_at_5,
        recall_at_10,
        p95_latency_ms,
        idle_rss_mb,
        index_rss_mb,
        cold_start_ms,
        reindex_ms,
    })
}

/// Render a report as a Phase 18 evidence markdown table.
pub fn render_evidence_md(report: &MeasureReport) -> String {
    let fmt_opt = |v: Option<f64>| v.map(|x| format!("{x:.2}")).unwrap_or_else(|| "n/a".into());
    format!(
        "# Phase 18 spike — `{name}`\n\n\
         > Auto-generated by `contextforge-bench` (task-18.2 harness). 5-dimension measurement.\n\n\
         | dimension | value |\n|---|---|\n\
         | backend | `{name}` |\n\
         | corpus size n | {n} |\n\
         | dim | {dim} |\n\
         | recall@5 | {r5:.4} |\n\
         | recall@10 | {r10:.4} |\n\
         | P95 latency (ms) | {p95:.3} |\n\
         | idle RSS (MB) | {idle} |\n\
         | index RSS (MB) | {index} |\n\
         | cold-start (ms) | {cold:.3} |\n\
         | reindex (ms) | {reindex:.3} |\n\n\
         ## Trade-off discussion\n\n<filled-by-backend-task>\n",
        name = report.backend_name,
        n = report.n,
        dim = report.dim,
        r5 = report.recall_at_5,
        r10 = report.recall_at_10,
        p95 = report.p95_latency_ms,
        idle = fmt_opt(report.idle_rss_mb),
        index = fmt_opt(report.index_rss_mb),
        cold = report.cold_start_ms,
        reindex = report.reindex_ms,
    )
}
