// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: contextforge/v1/index.proto

// FROZEN at schema_version "0.1" — see context.proto CONTRACT FREEZE RULE
// (only add fields, never delete or renumber tags).
// Phase 9 task-9.1: add-only extension for CLI data plane (ADR-013).

package contextforgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexRequest — POST /v1/index request (Phase 9 task-9.1 / ADR-013).
// SCAN_PATH mode (v0.2 only): server scans source_path filesystem,
// applies denylist / secret redaction, writes Tantivy + SQLite.
type IndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourcePath   string `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`       // absolute path; required
	DataDir      string `protobuf:"bytes,2,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`                // collection data root (~/.contextforge/ or override)
	CollectionId string `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // required; defaults to "default" if empty on server
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextforge_v1_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contextforge_v1_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_contextforge_v1_index_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *IndexRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *IndexRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

// IndexProgress — streaming progress update.
// Server sends >=1 message; final message has done=true.
// On error: in-band via the error field on the final (done=true) message.
type IndexProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilesProcessed        int64  `protobuf:"varint,1,opt,name=files_processed,json=filesProcessed,proto3" json:"files_processed,omitempty"`
	FilesSkippedDenied    int64  `protobuf:"varint,2,opt,name=files_skipped_denied,json=filesSkippedDenied,proto3" json:"files_skipped_denied,omitempty"`
	FilesSkippedRedaction int64  `protobuf:"varint,3,opt,name=files_skipped_redaction,json=filesSkippedRedaction,proto3" json:"files_skipped_redaction,omitempty"`
	ChunksWritten         int64  `protobuf:"varint,4,opt,name=chunks_written,json=chunksWritten,proto3" json:"chunks_written,omitempty"`
	CurrentFile           string `protobuf:"bytes,5,opt,name=current_file,json=currentFile,proto3" json:"current_file,omitempty"` // path being processed (last seen); empty on final
	Done                  bool   `protobuf:"varint,6,opt,name=done,proto3" json:"done,omitempty"`
	Error                 string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"` // empty unless terminal error
}

func (x *IndexProgress) Reset() {
	*x = IndexProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contextforge_v1_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexProgress) ProtoMessage() {}

func (x *IndexProgress) ProtoReflect() protoreflect.Message {
	mi := &file_contextforge_v1_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexProgress.ProtoReflect.Descriptor instead.
func (*IndexProgress) Descriptor() ([]byte, []int) {
	return file_contextforge_v1_index_proto_rawDescGZIP(), []int{1}
}

func (x *IndexProgress) GetFilesProcessed() int64 {
	if x != nil {
		return x.FilesProcessed
	}
	return 0
}

func (x *IndexProgress) GetFilesSkippedDenied() int64 {
	if x != nil {
		return x.FilesSkippedDenied
	}
	return 0
}

func (x *IndexProgress) GetFilesSkippedRedaction() int64 {
	if x != nil {
		return x.FilesSkippedRedaction
	}
	return 0
}

func (x *IndexProgress) GetChunksWritten() int64 {
	if x != nil {
		return x.ChunksWritten
	}
	return 0
}

func (x *IndexProgress) GetCurrentFile() string {
	if x != nil {
		return x.CurrentFile
	}
	return ""
}

func (x *IndexProgress) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *IndexProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_contextforge_v1_index_proto protoreflect.FileDescriptor

var file_contextforge_v1_index_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x6f,
	0x0a, 0x0c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x19, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x96, 0x02, 0x0a, 0x0d, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x64, 0x65, 0x6e, 0x69,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x53,
	0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x17,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x72, 0x65,
	0x64, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x53, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x52, 0x65, 0x64, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x5f, 0x77,
	0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x57, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f,
	0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6a, 0x69, 0x61, 0x6f, 0x79, 0x65, 0x7a,
	0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x66, 0x6f, 0x72, 0x67,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x66, 0x6f, 0x72, 0x67,
	0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contextforge_v1_index_proto_rawDescOnce sync.Once
	file_contextforge_v1_index_proto_rawDescData = file_contextforge_v1_index_proto_rawDesc
)

func file_contextforge_v1_index_proto_rawDescGZIP() []byte {
	file_contextforge_v1_index_proto_rawDescOnce.Do(func() {
		file_contextforge_v1_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_contextforge_v1_index_proto_rawDescData)
	})
	return file_contextforge_v1_index_proto_rawDescData
}

var file_contextforge_v1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contextforge_v1_index_proto_goTypes = []any{
	(*IndexRequest)(nil),  // 0: contextforge.v1.IndexRequest
	(*IndexProgress)(nil), // 1: contextforge.v1.IndexProgress
}
var file_contextforge_v1_index_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contextforge_v1_index_proto_init() }
func file_contextforge_v1_index_proto_init() {
	if File_contextforge_v1_index_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contextforge_v1_index_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contextforge_v1_index_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IndexProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contextforge_v1_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contextforge_v1_index_proto_goTypes,
		DependencyIndexes: file_contextforge_v1_index_proto_depIdxs,
		MessageInfos:      file_contextforge_v1_index_proto_msgTypes,
	}.Build()
	File_contextforge_v1_index_proto = out.File
	file_contextforge_v1_index_proto_rawDesc = nil
	file_contextforge_v1_index_proto_goTypes = nil
	file_contextforge_v1_index_proto_depIdxs = nil
}
